title: DJ Dong # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly analytical and detail-oriented data scientist who knows SQL, Python and SAS. Has a deep level of understanding of mathematics including but not limited to linear algebra and multivariable calculus.

  <br><br>
  Skilled in data analysis and visualization, and familiar with machine learning algorithms such as linear and logistic regression, k nearest neighbors, decision trees and random forests, and deep neural nets. Excellent written and oral communication skills built from teaching college level mathematics to non-math majors.

  <br><br>
  <a href="https://www.linkedin.com/in/ustcdj/">My Resume</a>

  <br><br>
  <a href="https://www.linkedin.com/in/ustcdj/">My LinkedIn</a>



theme: jekyll-theme-minimal
google_analytics: UA-177775255-1 # your Google Analytics tracking ID here
