title: DJ Dong # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly analytical and detail-oriented data scientist. Skilled in data analysis and visualization, and familiar with machine learning algorithms such as supervised learning, unsupervised learning, neuron networks. Excellent written and oral communication skills built from years of presenting analysis results to seniro management.

  <br><br>

  <br><br>
  <a href="https://www.linkedin.com/in/ustcdj/">My Resume</a>

  <br><br>
  <a href="https://www.linkedin.com/in/ustcdj/">My LinkedIn</a>



theme: jekyll-theme-minimal
google_analytics: UA-177775255-1 # your Google Analytics tracking ID here
