title: DJ Dong # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    5 years SQL
    5 years Tableau
    2 years Python
    2 years SAS
    5 years data analyst
    2 years data science, machine learning

  <br><br>
  Love using data to answer business questions, deliver effective and impactful solutions.
  Highly analytical and detail-oriented. Skilled in data analysis and visualization,
  and proficient at machine learning algorithms such as supervised learning and unsupervised learning.
  Excellent written and oral communication skills built from years of presenting analysis results to
  senior management.

  <br><br>

  <br><br>
  <a href="https://ustcdj.github.io/resume/">My Resume</a>

  <br><br>
  <a href="https://www.linkedin.com/in/ustcdj/">My LinkedIn</a>



theme: jekyll-theme-minimal
google_analytics: UA-177775255-2 # your Google Analytics tracking ID here 251392170
